Mutation:
    type: object
    config:
        fields:
            introduceShip:
                builder: Relay::Mutation
                builderConfig:
                    inputType: IntroduceShipInput
                    payloadType: IntroduceShipPayload
                    mutateAndGetPayload: "@=mutation('create_ship', [value['shipName'], value['factionId']])"
