language: php

php:
    - 5.6

services:
  - mysql

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - composer selfupdate

install: composer update --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database starwars_test;'

script: bin/phpunit
